version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb+srv://admin:admin@crypto.g1gwxfl.mongodb.net
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: